nysenate/NYSenate.gov-Website-D9

config/sync/views.view.events.yml, config/sync/views.view.newsroom.yml, config/sync/views.view.senator_microsite_content.yml, web/themes/custom/nysenate_theme/src/templates/views/views-view-unformatted--microsite-newsroom-content.html.twig, web/themes/custom/nysenate_theme/src/templates/views/views-view-unformatted--newsroom--press-releases.html.twig, web/themes/custom/nysenate_theme/src/templates/views/views-view-unformatted--senator-microsite-content--article-footer.html.twig
- Switches sitewide/senator newsroom/footer news views to use ajax pager
- Changes calendar day view to show all, and week/month to use ajax pager 
- Removes hard coded infinite scroll code from relevant templates
=> Temp fix for views infinite scroll, switch to ajax pager

web/profiles/custom/nysenate/config/prod/reroute_email.settings.yml
Forgot to put reroute email settings in prod folder after deleting from global config :-|
=> Reroute email settings prod config file

config/sync/core.extension.yml
uninstalls these Rain feature modules (there are a couple more to go, but this is start):
- rain_views
- rain_text
- rain_slider
- rain_slider_item
- rain_quote_carousel
- rain_quote
- rain_map
- rain_hero
- rain_gallery_carousel
- rain_gallery_item
- rain_gallery
- rain_media
- rain_form
- rain_embed
- rain_card_list
- rain_card
- rain_breaker
- rain_block_quote
- rain_block_card
- rain_accordion
- rain_accordion_item
- rain_paragraphs
- rain_styles
- rain_blocks
=> STEP 1 Rain Admin Removal: Remove feature only modules

pantheon.yml, web/private/hooks/afterCloudCreate.php
https://docs.pantheon.io/guides/quicksilver/hooks#hooks
We needed the `create_cloud_development_environment` to be added to Pantheon.yml so the first time after a multidev env is created, it will import config. We may also need one for database syncs.
=> Hotfix: adding an additional Pantheon quicksilver hook

config/sync/views.view.newsroom.yml, config/sync/views.view.senator_microsite_content.yml, web/themes/custom/nysenate_theme/src/patterns/components/nysenate-tabs/nysenate-tabs.js
1. Fixes pagination issue on newsroom views (by switching to infinite scroll, as recommended by Alison)
2. Fixes secondary bug on the main newsroom where tabbing between "All news" and "Press Releases" then using pagination would break the tabs
=> Aten NYS 52: Fix pagination issue on newsroom views

config/sync/charts.settings.yml
config resulted from steve's PR-83, which updated the Chart's module
=> Adds chart module config from database update

config/sync/views.view.advanced_legislation_search.yml, web/modules/custom/nys_legislation_explorer/src/Form/SearchAdvancedLegislationForm.php, web/themes/custom/nysenate_theme/src/patterns/components/pager/pager.twig, web/themes/custom/nysenate_theme/src/templates/content/node--meeting--search-teaser.html.twig
- Fixes bug when paginating beyond 5th results page
- Fixes advanced search bugs:
1. Resolution sort order incorrect
2. Transcript refine search not preserving search type
3. Refine search form setting month to “January“ incorrectly
4. Committee Meeting Agenda date defaulting to today’s date
5. 2023 Public Hearing Transcript’s showing wrong date
=> Aten NYS-57: Advanced legislation search issues

config/sync/core.entity_form_display.node.in_the_news.default.yml, config/sync/core.entity_form_display.node.video.default.yml, web/modules/custom/nys_senators/nys_senators.module, web/modules/custom/nys_senators/src/SenatorsHelper.php, web/modules/custom/nys_users/src/UsersHelper.php
This was created in response to https://atendesign.atlassian.net/browse/NYS-64
Per @routinet 's direction, I added a couple new methods to web/modules/custom/nys_users/src/UsersHelper.php
Totally open to naming convention there. Naming stuff is hard!!!
I ended up using a `hook_query_TAG_alter` because it will be a more flexible solution if we need to further limit access to taxonomy terms for MCP users, etc.
=> NYS-64: MCP role should not have access to all committees

web/modules/custom/nys_registration/src/Controller/NysUserController.php, web/profiles/custom/nysenate/config/dev/reroute_email.settings.yml, web/profiles/custom/nysenate/config/develop/reroute_email.settings.yml, web/profiles/custom/nysenate/config/local/email_tfa.settings.yml, web/profiles/custom/nysenate/config/local/reroute_email.settings.yml, web/profiles/custom/nysenate/config/multidev/reroute_email.settings.yml, web/profiles/custom/nysenate/config/test/reroute_email.settings.yml, web/sites/default/settings.php
1. Enables email TFA and adds override for password reset form
2. Removes default reroute_email override from settings.php and moves them into config split
=> Feature: Enables email TFA and adds override for password reset form

.github/workflows/pantheon-deploy-multidev.yml
@routinet Quicksilver didn't give me enough cross-environment information to be able to accomplish this, but terminus does, so I'm trying it here in the GH Action. This would copy the file from `dev`.
=> NYS-65: copies private settings file when creating a MD env

config/sync/views.view.events.yml, web/themes/custom/nysenate_theme/src/templates/views/views-view--events.html.twig
By rendering promo banner through main view instead of template, avoiding Views AJAX issue.
=> Fix: prevent event listing page promo banner duplication 

.github/workflows/pantheon-deploy-multidev.yml, web/themes/custom/nysenate_theme/src/patterns/components/event-calendar/event-calendar.js
By removing broken exposed filter date input manipulation Javascript. Additionally, hide duplicate/misleading date filter from week and month views.
=> Fix: resolve bug affecting all exposed filters on the month display of the event listing page

config/sync/ultimate_cron.job.nys_comment_cron.yml, web/modules/custom/nys_comment/nys_comment.install, web/modules/custom/nys_comment/nys_comment.module
Dev note: implemented cron hook in nys_comment module instead of nys_bills module with an eye towards similar comment automation in other content types. Open to feedback if this doesn't match business rules.
=> Feature/aten nys 71  automated comment closing session year

config/sync/config_split.config_split.local.yml, web/themes/custom/nysenate_theme/src/patterns/components/nysenate-header/nysenate-header.js
This PR addresses 2 potential bugs:
1. Remove orphaned migrate_devel from local config split
2. Disables homepage in-session behavior for actionbar, due to JS glitches when minimizing / expanding on scroll
I carved this out as a separate PR from my main NYS-79 branch, in case there's a good reason for either item above to be this way.
For item 2 above, note that this means the homepage "in session" actionbar follows the user on scroll (like it does for typical interior pages). If we want the actionbar to collapse in this context, we'll want to fix the JS code that handles this, as right now the code is causing misfiring expanding / collapsing actionbar animations, in addition to the header "ghosting" effected noted in NYS-68.
=> Bug fixes resolved during NYS-79 development

web/themes/custom/nysenate_theme/nysenate_theme.theme, web/themes/custom/nysenate_theme/src/patterns/components/hero/hero.twig, web/themes/custom/nysenate_theme/src/patterns/components/nysenate-header/nysenate-header.js, web/themes/custom/nysenate_theme/src/patterns/components/nysenate-header/nysenate-header.scss, web/themes/custom/nysenate_theme/src/patterns/components/nysenate-header/nysenate-header.twig
This PR resolves 2 JS issues that affect performance and stability of senator microsite sections:
1. The Drupal/PHP layer was rendering the same full size header on microsite interior pages (Event, Press Release, etc) as on the full senator landing page, hidden by CSS. Then, using JS, the theme was manipulating that full header into the collapsed header users saw. This PR ensures the interior page collapsed header is rendered correctly by default, and that JS is only needed for additional UX enhancements. This way, any issues in the JS-layer won't break the interior pages headers.
2. JS code was cloning the senator image into place on each page scroll, leading to potential performance issues and visual glitches. This PR clones the senator image once at an earlier rendering stage, removing …
=> Feature/Aten NYS 79: remove senator header JS dependency

config/sync/views.view.issues_listings.yml
This PR fixes the issue of the issues explorer page (/explore-issues) not loading--or loading very slowly--for anonymous users by removing an unused flag field and relationship from one of the views on that page.
=> NYS-101: Fix issue explorer not loading for anonymous users

web/modules/custom/nys_bill_vote/src/Form/BillVoteWidgetForm.php
Steps to reproduce:
1. Log in as an authenticated user
2. Navigate to: https://www.nysenate.gov/newsroom/press-releases/2024/senate-bolsters-educator-diversity-efforts-new-york-state
3. Click “Aye“ under bill “2023-S1988“
4. Result: Redirected to bill “2023-S3385A“
5. Expected result: Redirected to bill “2023-S1988“
**Technical note for @routinet and @aheaphy:** this fixes a bug in the BillVoteWidgetForm::voteAjaxCallback method by getting the bill ID from the form input (which is always correct) vs. the form build info (which is incorrect in contexts where there are multiple vote widgets present). There may still be an underlying bug on the form build stage, but I avoided larger refactors there as I know we plan to rework this form anyways.
=> NYS-107: Fix bug where wrong bill targeted when multiple bill vote widgets are on same page

config/sync/gin.settings.yml, config/sync/google_tag.container.G-01H6J3L7N6.656e09e463cc88.61658280.yml
PLUS: removes gin sub tool bar from frontend (which is already done on live, so need it in config too)
=> Uncheck privacy consent policy for google tags

composer.json, composer.lock, config/sync/diff.settings.yml, config/sync/flood_control.settings.yml, config/sync/scheduler.settings.yml
**Contrib modules updated:**
drupal/better_exposed_filters (6.0.3 => 6.0.5):
drupal/charts (5.0.12 => 5.0.13): 
drupal/turnstile (1.1.8 => 1.1.9)
drupal/config_ignore (3.2.0 => 3.3.0)
drupal/diff (1.1.0 => 1.3.0):
drupal/email_registration (2.0.0-rc4 => 2.0.0-rc5)
drupal/flood_control (2.3.3 => 2.3.4):
drupal/geolocation (3.12.0 => 3.13.0):
drupal/override_node_options (2.7.0 => 2.8.0):
drupal/paragraphs_features (2.0.0-beta4 => 2.0.0):
drupal/scheduler (2.0.1 => 2.0.3)
drupal/token (1.13.0 => 1.14.0)
drupal/upgrade_status (4.1.0 => 4.3.1)
drupal/views_load_more (2.0.0-rc2 => 2.0.0)
drupal/gin (3.0.0-rc9 => 3.0.0-rc10)
drupal/entity_print (2.13.0 => 2.14.0):
dompdf/dompdf (v2.0.4 => v2.0.8)
**Database Updates**
Module          Update ID   Type            Description …
=> Contrib module updates and related config

web/themes/custom/nysenate_theme/nysenate_theme.theme
Dev note: Issue was caused by unnecessary webform node re-rendering. This PR also eliminates unnecessary node re-rendering for all "microsite" nodes: article, event, honoree, in_the_news, petition, webform, video (as defined at nysenate_theme.theme:2402).
=> NYS-110: Fix issue with multistep (including preview step) webforms using Turnstile captcha

composer.json, composer.lock, config/sync/core.extension.yml, web/modules/custom/nys_bill_vote/src/Form/BillVoteWidgetForm.php, web/modules/custom/nys_dashboard/src/Form/ManageDashboardForm.php, web/profiles/custom/nysenate/config/local/email_tfa.settings.yml
Uninstall:
jquery_ui_datepicker
Module updates:
drupal/better_exposed_filters (6.0.5 => 6.0.6)
drupal/ctools (4.0.4 => 4.1.0)
drupal/entityqueue (1.7.0 => 1.8.0)
drupal/environment_indicator (4.0.17 => 4.0.18)
drupal/gin_toolbar (1.0.0-rc5 => 1.0.0-rc6)
drupal/google_tag (2.0.4 => 2.0.5)
drupal/jquery_ui_autocomplete (2.0.0 => 2.1.0)
drupal/jquery_ui_menu (2.0.0 => 2.1.0)
drupal/jquery_ui_menu(
drupal/jquery_ui_datepicker (2.0.0 => 2.1.0)
drupal/jquery_ui_slider (2.0.0 => 2.1.0)
drupal/key (1.17.0 => 1.18.0)
drupal/login_history (2.0.0-alpha1 => 2.0.0-alpha3)
drupal/search_api_pantheon (8.1.8 => 8.1.9)
drupal/views_bulk_operations (4.2.6 => 4.2.7)
drupal/viewsreference (2.0.0-beta7 => 2.0.0-beta8):
drupal/views_year_filter (2.1.3 => 2.1.4)
drupal/gin (3.0.0-rc10 => 3.0.0-rc11) …
=> Contrib module updates

web/modules/custom/nys_openleg_api/src/Plugin/OpenlegApi/Response/PublicHearingUpdateList.php, web/modules/custom/nys_openleg_imports/src/Commands/OpenlegImport.php
- Clean up usage of raw vs resolved command-line options
- Implement OL API changes to public hearing returns
- Address Drush's removal of success/fail constants
- Clean up old sniffer canary (yay! it's working!)
=> NYS-16492: public hearing updates not importing

config/sync/user.role.microsite_content_producer.yml, web/modules/custom/nys_senators/nys_senators.module, web/modules/custom/nys_senators/src/Access/McpBlockContentAccessControlHandler.php
Note that the related hotfix in https://github.com/nysenate/NYSenate.gov-Website-D9/pull/226 revokes all MCP block content access. This is the long term fix.
=> NYS 168: Restrict MCP block content edit access to blocks linked to their managed senators

composer.json, composer.lock, config/sync/admin_toolbar.settings.yml, config/sync/admin_toolbar_tools.settings.yml, config/sync/core.extension.yml, config/sync/environment_indicator.settings.yml, config/sync/geocoder.settings.yml, config/sync/key.key.turnstile.yml, config/sync/turnstile.settings.yml
drupal/core-recommended (10.4.7 => 10.4.8)
Contrib:
drupal/admin_toolbar (3.5.3 => 3.6.1)
drupal/charts (5.1.5 => 5.1.6)
drupal/turnstile (1.1.17 => 1.1.20) [NOTE: updated key config https://www.drupal.org/project/turnstile/issues/3516763]
drupal/diff (1.8.0 => 1.9.0)
drupal/flag (4.0.0-beta6 => 4.0.0-beta7) {NOTE: updated patch file for "3336839 - FlagCountManager: Call to a member function id() on null]
drupal/geocoder (4.28.0 => 4.29.0)
drupal/metatag (2.1.0 => 2.1.1):
drupal/twig_tweak (3.4.0 => 3.4.1)
drupal/views_data_export (1.5.0 => 1.6.0)
drupal/environment_indicator (4.0.21 => 4.0.22) [NOTE: removed patch, no longer needed, also, new submodule available for integration with Gin Toolbar https://www.drupal.org/project/environment_indicator/releases/4.0.22]
Database updates:
Module …
=> Drupal core update 10.4.8, plus contrib modules
