web/modules/custom/nys_openleg/nys_openleg.module
web/modules/custom/nys_openleg/src/Api/RequestPluginBase.php
web/modules/custom/nys_openleg/src/Controller/MainController.php
web/modules/custom/nys_openleg/src/Plugin/OpenlegApi/Response/ResponseSearch.php
web/modules/custom/nys_openleg/templates/nys-openleg-search-results.html.twig

Fixes controller to properly track and use page marker.  Also:
- Fixes pager to use proper URL
- Forces detected search term from POST/query string to populate in the route parameter
- Added total data point to rendered results

Fix per-page limits to OpenLeg search form, minor cosmetic improvement

---

config/sync/contact.form.summer_reading.yml
config/sync/core.entity_form_display.block_content.video.default.yml
config/sync/core.entity_form_display.node.video.default.yml
config/sync/core.entity_form_display.node.webform.default.yml
config/sync/field.field.block_content.video.field_video.yml
web/modules/custom/nys_access_permissions/nys_access_permissions.module
web/themes/custom/nysenate_theme/nysenate_theme.theme

Ticket 15697: Allows MCPs to see settings tab on webforms
Ticket 15667: Fixes MCPs not able to add  Video content
Other: changes email on summer reading form

Fix webform settings tab and Video content type

---

web/modules/custom/nys_bills/src/Milestones.php
web/modules/custom/nys_metatags/nys_metatags.module
web/themes/custom/nysenate_theme/nysenate_theme.theme

Plus Steve's changes:
- Adjust type hinting in metatags
- Correct calling convention for getFromNode()

Fixes No Title on microsite news view

---

config/sync/views.view.committee_content.yml
config/sync/views.view.committee_meetings.yml
config/sync/views.view.senator_events.yml
config/sync/views.view.summer_reading_admin.yml
web/themes/custom/nysenate_theme/src/patterns/components/nysenate-search-results-listing/nysenate-search-results-listing.scss
web/themes/custom/nysenate_theme/src/patterns/global/global.scss

- Adds senator exposed filter to reading results
- Adds news heading to meeting page news view, plus padding and border styles 
- Fixes senator events page view to display all items 
- Removes no show featured story text from committee page

Views updates

---

web/themes/custom/nysenate_theme/src/patterns/components/hero/hero.twig

SEO -- capitals

---

config/sync/rabbit_hole.behavior_settings.taxonomy_vocabulary_districts.yml
config/sync/views.view.honoree_profiles.yml
web/themes/custom/nysenate_theme/nysenate_theme.theme
web/themes/custom/nysenate_theme/src/patterns/components/district/district.json
web/themes/custom/nysenate_theme/src/patterns/components/district/district.twig
web/themes/custom/nysenate_theme/src/templates/taxonomy-term/taxonomy-term--districts--district.html.twig
web/themes/custom/nysenate_theme/src/templates/taxonomy-term/taxonomy-term--districts.html.twig

-Removes rabbit hole restrictions on taxonomy district pages
-Adds district template with link to senators's microsites

Restores taxonomy district pages to the site

---

composer.json
composer.lock
config/sync/captcha.settings.yml
config/sync/core.extension.yml
config/sync/turnstile.settings.yml

The site and secret key has been added to the private_settings.php file and will be FTP'd

Turnstile module and config

---

config/sync/config_split.config_split.local.yml
config/sync/views.view.senator_contact.yml

Plus fixed local config split for captcha

Fix permissions on senator contact submissions view

---

.github/workflows/pantheon-deploy-multidev.yml
.github/workflows/pantheon-multidev-cleanup.yml
.github/workflows/pantheon-refresh-dev.yml

This PR will not impact Pantheon at all outside of how we work with it for multidevs, etc. There are three main commits that show the work accomplished here.

Hotfix/nys-45: Github Action Improvments

---

web/modules/custom/nys_registration/src/Form/RegisterForm.php
web/themes/custom/nysenate_theme/src/patterns/components/district/district.twig
web/themes/custom/nysenate_theme/src/patterns/components/nysenate-user-profile/nysenate-user-profile.twig
web/themes/custom/nysenate_theme/src/templates/register-form-step2.html.twig

1. Adds district map to user registration workflow step 2
2. Adds support for zipcodes entered with preceding or trailing whitespace

NYS-43: District Map for User Registration

---

config/sync/core.entity_form_display.paragraph.votes.default.yml
config/sync/core.entity_view_display.paragraph.votes.default.yml
config/sync/field.field.paragraph.votes.field_remote_voting.yml
config/sync/field.storage.paragraph.field_remote_voting.yml
web/modules/custom/nys_bills/src/BillsHelper.php
web/modules/custom/nys_openleg_imports/src/Plugin/OpenlegImportProcessor/Bills.php
web/themes/custom/nysenate_theme/nysenate_theme.theme
web/themes/custom/nysenate_theme/src/patterns/components/resolution-page/resolution-page.scss
web/themes/custom/nysenate_theme/src/templates/content/node--bill.html.twig

- Add new 'field_remote_voting' to vote paragraphs
- Add processing for remote voting data to OpenLeg bill importer
- Refactor theme layer for more efficient compilation of vote data
- Add remote voting indicators to bill twig template

Add remote voting data to bill pages

---

config/sync/views.view.committee_meetings.yml
config/sync/views.view.content.yml
config/sync/views.view.homepage_events.yml
web/themes/custom/nysenate_theme/src/patterns/components/nysenate-legislative-events/nysenate-legislative-events.scss
web/themes/custom/nysenate_theme/src/templates/views/views-view--homepage-events--block-1.html.twig

And removes date sort on agenda committee view

Fixes in session view output and placement of link to event page

---

config/sync/views.view.comment.yml
config/sync/views.view.content.yml

and removes microsite page type from admin content view

Fixes parent tab on comments view 

---

web/modules/custom/nys_accumulator/nys_accumulator.install
web/modules/custom/nys_accumulator/src/AccumulatorEntry.php
web/modules/custom/nys_accumulator/src/EventSubscriber/GeneralEventSubscriber.php
web/modules/custom/nys_accumulator/src/Service/Accumulator.php

- Changes msg_* fields to event_* fields
- Updates accumulator/accumulator_archive table field names
- Updates existing accumulator data type and action values
- See redmine #16060, #16047

Update accumulator fields

---

config/sync/core.entity_form_display.taxonomy_term.majority_issues.default.yml
config/sync/field.field.taxonomy_term.majority_issues.field_teaser.yml
config/sync/field.storage.node.field_ustream.yml
config/sync/views.view.home_majority_issue.yml
web/themes/custom/nysenate_theme/nysenate_theme.theme
web/themes/custom/nysenate_theme/src/patterns/components/hero/hero.json
web/themes/custom/nysenate_theme/src/patterns/components/hero/hero.twig
web/themes/custom/nysenate_theme/src/patterns/components/landing-page-hero/landing-page-hero.scss
web/themes/custom/nysenate_theme/src/patterns/components/nysenate-actionbar/nysenate-actionbar.scss
web/themes/custom/nysenate_theme/src/patterns/components/nysenate-actionbar/nysenate-actionbar.twig
web/themes/custom/nysenate_theme/src/patterns/components/nysenate-header/nysenate-header.json
web/themes/custom/nysenate_theme/src/patterns/components/session/session.scss
web/themes/custom/nysenate_theme/src/templates/block/block--views-block--homepage-hero-homepage-hero.html.twig
web/themes/custom/nysenate_theme/src/templates/content/node--meeting--full.html.twig
web/themes/custom/nysenate_theme/src/templates/content/node--public-hearing--full.html.twig
web/themes/custom/nysenate_theme/src/templates/content/node--session--full.html.twig
web/themes/custom/nysenate_theme/src/templates/field/field--node--field-ustream.html.twig
web/themes/custom/nysenate_theme/src/templates/field/field--node--field-video-redirect.html.twig
web/themes/custom/nysenate_theme/src/templates/layout/page.html.twig
web/themes/custom/nysenate_theme/src/templates/misc/flag--follow-committee.html.twig
web/themes/custom/nysenate_theme/src/templates/misc/flag--follow-issue.html.twig

-Adds committee name to action bar
-Adds and fixes icon to follow part of action bar
-Fixes meeting streaming redirect field
-Fixes home page streaming if redirect field is used
-Fixes mobile display of streaming videos on node pages

Fixes to committee and issues action bar and Ustream fields

---

config/sync/core.entity_form_display.node.event.default.yml
config/sync/core.entity_view_display.node.event.card.yml
config/sync/core.entity_view_display.node.event.default.yml
config/sync/core.entity_view_display.node.event.featured_content.yml
config/sync/core.entity_view_display.node.event.search_index.yml
config/sync/core.entity_view_display.node.event.search_teaser.yml
config/sync/core.entity_view_display.node.event.teaser.yml
config/sync/core.entity_view_display.node.event.upcoming_event.yml
config/sync/core.entity_view_display.node.public_hearing.default.yml
config/sync/field.field.node.event.field_video_redirect.yml
web/themes/custom/nysenate_theme/src/patterns/components/event/event.scss
web/themes/custom/nysenate_theme/src/patterns/components/nysenate-featured-event/nysenate-featured-event.scss
web/themes/custom/nysenate_theme/src/patterns/components/nysenate-legislative-events/nysenate-legislative-events.scss
web/themes/custom/nysenate_theme/src/patterns/components/session/session.scss
web/themes/custom/nysenate_theme/src/templates/content/node--event--full.html.twig
web/themes/custom/nysenate_theme/src/templates/content/node--meeting--full.html.twig
web/themes/custom/nysenate_theme/src/templates/content/node--public-hearing--full.html.twig
web/themes/custom/nysenate_theme/src/templates/content/node--session--full.html.twig
web/themes/custom/nysenate_theme/src/templates/views/views-view-fields--events.html.twig

- adds maj issue tag to public hearing template, and 
- puts committee tag with issue tags, and 
- removes other references to issues/committees to make consistent with other content types

Adds redirect field to events and other fixes

---

web/themes/custom/nysenate_theme/nysenate_theme.theme
web/themes/custom/nysenate_theme/src/patterns/components/nysenate-actionbar/nysenate-actionbar.twig
web/themes/custom/nysenate_theme/src/patterns/components/nysenate-header/nysenate-header.scss
web/themes/custom/nysenate_theme/src/patterns/components/nysenate-header/nysenate-header.twig

Notes
- Only affects following content types: 'event', 'in_the_news', 'article', 'video'.
- Maintains senator's banner color.

Feature: If microsite page is assigned to committee, show committee action bar in place of senator banner

---

.github/workflows/run-visual-regression-tests-manual.yml
tests/cypress/cypress/e2e/visual-regression.cy.js

Minor change here to see if waking environments solves so issues we've been seeing with VRT running.

NYS-20: adds terminus and env:wake command to the github action

---

config/sync/views.view.events.yml
config/sync/views.view.homepage_events.yml

dates without end date were not displaying with date element

Fixes home page events view

---

composer.json
config/sync/config_split.config_split.local.yml
config/sync/webform.webform.school_form_earth_day.yml
config/sync/webform.webform.school_form_thanksgiving.yml

Results tab and show student element show just for admin role
Removed migrate devel from local config split

Fixes for school forms

---

config/sync/core.entity_view_display.node.resolution.pdf.yml
config/sync/entity_print.print_engine.dompdf.yml
config/sync/entity_print.settings.yml
config/sync/user.role.anonymous.yml
config/sync/user.role.authenticated.yml
web/themes/custom/nysenate_theme/nysenate_theme.theme
web/themes/custom/nysenate_theme/src/patterns/components/resolution-page/resolution-page.scss
web/themes/custom/nysenate_theme/src/templates/content/node--resolution.html.twig
web/themes/custom/nysenate_theme/src/templates/print/node--resolution--pdf.html.twig

Fixes:
- resolution pdf download, using entity print
- fixes link to senator/sponsor microsite
- fixes image if statement

Resolution pdf download

---

web/modules/custom/nys_school_forms/src/Form/SchoolFormSearchForm.php
web/modules/custom/nys_school_forms/src/SchoolFormsService.php

Also fixes error on date sort, but does not fix the fact that it returns no results

Fixes sort order on school submissions admin page

---

config/sync/core.entity_view_display.node.article.pdf.yml
config/sync/image.style.square.yml
config/sync/user.role.anonymous.yml
config/sync/user.role.authenticated.yml
config/sync/views.view.school_leadership.yml
config/sync/webform.webform.youth_leadership.yml
web/themes/custom/nysenate_theme/nysenate_theme.info.yml
web/themes/custom/nysenate_theme/nysenate_theme.libraries.yml
web/themes/custom/nysenate_theme/print/print-styles.css
web/themes/custom/nysenate_theme/src/patterns/components/article-page/article-page.scss
web/themes/custom/nysenate_theme/src/patterns/global/fonts/_fonts.scss
web/themes/custom/nysenate_theme/src/patterns/global/global.scss
web/themes/custom/nysenate_theme/src/patterns/global/print/_print-styles.scss
web/themes/custom/nysenate_theme/src/templates/content/node--article--full.html.twig
web/themes/custom/nysenate_theme/src/templates/print/node--article--pdf.html.twig

[still needs formatting, just getting multi-dev started]

Adds entity print template and link on article page

---

web/themes/custom/nysenate_theme/src/templates/views/views-view--committee-meetings--agenda.html.twig

Quick fix to meeting agenda template

---

web/modules/custom/nys_school_forms/src/Plugin/Block/SenatorMicrositeSchoolFormSubmissions.php

- Updates earth day display for 2024
- separates build for thanksgiving and earthday for unique titles

DEPLOY April 12 -- Update dates for Earth Day 2024

---

config/sync/core.entity_view_display.node.in_the_news.featured_content.yml
config/sync/views.view.featured_content_entref.yml
web/themes/custom/nysenate_theme/nysenate_theme.theme
web/themes/custom/nysenate_theme/src/patterns/components/featured-story/featured-story.twig
web/themes/custom/nysenate_theme/src/patterns/components/nysenate-promotional-banner-list/nysenate-promotional-banner-list.scss
web/themes/custom/nysenate_theme/src/templates/content/node--in-the-news--featured-content.html.twig
web/themes/custom/nysenate_theme/src/templates/content/node--in-the-news--full.html.twig

Also, fix issue if statement on in the news node template

Allow In the News to be featured content on microsite home page

---

.gitignore
config/sync/config_ignore.settings.yml
config/sync/core.entity_form_display.node.student_program.default.yml
config/sync/core.entity_view_display.node.student_program.default.yml
config/sync/core.entity_view_display.node.student_program.search_index.yml
config/sync/core.entity_view_display.node.student_program.teaser.yml
config/sync/field.field.node.student_program.field_webform.yml
config/sync/field.storage.node.field_webform.yml
config/sync/views.view.mysenate_rss.yml
config/sync/webform.webform.summer_internship_application.yml
web/themes/custom/nysenate_theme/src/templates/content/node--student-program--full.html.twig
web/themes/custom/nysenate_theme/src/templates/views/views-view--student-programs-news.html.twig

Update student program content type with webform field 
Update config ignore

Add summer student internship webform

---

config/sync/views.view.news_by_issue.yml
web/themes/custom/nysenate_theme/nysenate_theme.theme
web/themes/custom/nysenate_theme/src/templates/semanticviews-row--news-by-issue--meeting-by-issue.html.twig
web/themes/custom/nysenate_theme/src/templates/semanticviews-row--news-by-issue--news-by-bill.html.twig

Template fixes for issue page views

---

web/themes/custom/nysenate_theme/src/patterns/components/nysenate-header/nysenate-header.js

Fixes:
1. Issue where search doesn't activate for users with elevated roles
2. Restores menu access for elevated users on mobile devices (separate issue identified during testing)

NYS-108: Fixes issue where search doesn't activate for users with elevated roles

---

.gitignore
config/sync/block.block.footerright.yml
config/sync/config_ignore.settings.yml
config/sync/gin.settings.yml
config/sync/system.menu.footer-right.yml
config/sync/views.view.senators_admin_list.yml
config/sync/webform.webform.contact.yml
config/sync/webform.webform.contact_website_issues.yml
web/themes/custom/nysenate_theme/src/patterns/components/featured-story/featured-story.twig
web/themes/custom/nysenate_theme/src/patterns/components/newsroom-landing/newsroom-landing.scss
web/themes/custom/nysenate_theme/src/patterns/components/newsroom-landing/newsroom-landing.twig
web/themes/custom/nysenate_theme/src/patterns/components/nysenate-footer/nysenate-footer.scss
web/themes/custom/nysenate_theme/src/patterns/components/nysenate-header/nysenate-header.scss
web/themes/custom/nysenate_theme/src/templates/layout/maintenance-page.html.twig
web/themes/custom/nysenate_theme/src/templates/layout/page--403.html.twig
web/themes/custom/nysenate_theme/src/templates/layout/page--404.html.twig
web/themes/custom/nysenate_theme/src/templates/layout/page--explore-issues.html.twig
web/themes/custom/nysenate_theme/src/templates/layout/page--node--microsite-page.html.twig
web/themes/custom/nysenate_theme/src/templates/layout/page.html.twig
web/themes/custom/nysenate_theme/src/templates/navigation/menu--socials.html.twig

just getting feature multi-dev established, still working on this!!!

Initial set up for new footer design

---

web/themes/custom/nysenate_theme/src/patterns/components/article-page/article-page.scss
web/themes/custom/nysenate_theme/src/templates/content/node--video--full.html.twig

changes twig to show multi-value field

Show multi-value video field on video content type

---

web/themes/custom/nysenate_theme/nysenate_theme.theme

this fixes originally reported issue of /issues/budget page being broken

Add validation check for sponsor term

---

config/sync/block.block.dashboardactionbar_manage.yml
config/sync/block.block.exposed_form__my_dashboard__main.yml
config/sync/core.entity_form_mode.user.edit_account.yml
config/sync/core.entity_view_mode.node.my_dashboard_teaser.yml
config/sync/views.view.admin_microsite_content.yml
config/sync/views.view.advanced_legislation_search.yml
config/sync/views.view.committee_hero_banner.yml
config/sync/views.view.constituent_petitions_and_questionnaires.yml
config/sync/views.view.constituents.yml
config/sync/views.view.core_search.yml
config/sync/views.view.events.yml
config/sync/views.view.honoree_profiles.yml
config/sync/views.view.majority_issues.yml
config/sync/views.view.manage_staff_users.yml
config/sync/views.view.my_senator.yml
config/sync/views.view.open_data.yml
config/sync/views.view.questionnaires.yml
config/sync/views.view.school_leadership.yml
config/sync/views.view.senator_and_committee_lists.yml
config/sync/views.view.senator_events.yml
config/sync/views.view.senator_microsite_content.yml
web/modules/custom/nys_dashboard/nys_dashboard.module

Also addresses config being out of sync with upgraded module defaults

NYS 93: Fix dashboard exposed filters issues caching problem

---

web/modules/custom/nys_dashboard/src/Form/ManageDashboardForm.php

Other minor adjustments to comply with best practices.

Ensure subscriptions are canceled after unfollowing a bill from the dashboard

---

composer.json
composer.lock

drupal/core-dev (10.3.0 => 10.3.1)
drupal/address (2.0.1 => 2.0.2) -- d11 compatibility
drupal/charts (5.0.13 => 5.1.0) -- d11 compatibility
drupal/crop (2.3.0 => 2.4.0) -- d11 compatibility
drupal/environment_indicator (4.0.18 => 4.0.19 -- https://www.drupal.org/project/environment_indicator/releases/4.0.19
drupal/field_permissions (1.3.0 => 1.4.0) -- https://www.drupal.org/project/field_permissions/releases/8.x-1.4
drupal/key (1.18.0 => 1.19.0) -- https://www.drupal.org/project/key/releases/8.x-1.19
drupal/recaptcha (3.2.0 => 3.3.0): -- https://www.drupal.org/project/recaptcha/releases/8.x-3.3
drupal/semanticviews (3.0.0 => 3.1.0) -- Automated Project Update Bot fixes
drupal/stage_file_proxy (2.1.5 => 3.1.0) -- https://www.drupal.org/project/stage_file_proxy/releases/3.1.0 …

Drupal core 10.3.1 and contrib module updates

---

web/themes/custom/nysenate_theme/src/templates/taxonomy-term/taxonomy-term--districts.html.twig

fix value for senator variable on district template

Fix district template so Vacant District is not showing on all terms

---

config/sync/search_api.index.core_search.yml
config/sync/views.view.advanced_legislation_search.yml
web/modules/custom/nys_accumulator/src/Service/Accumulator.php
web/modules/custom/nys_legislation_explorer/src/Form/SearchAdvancedLegislationForm.php
web/modules/custom/nys_openleg/nys_openleg.module
web/modules/custom/nys_senators/src/SenatorsHelper.php
web/modules/custom/nys_senators/src/Service/Microsites.php
web/themes/custom/nysenate_theme/src/patterns/components/legislation-search-form/legislation-search-form.scss

Dev note: deploy of this will require reindexing Solr search using `drush sapi-i`

NYS 162: Add active revision filter to advanced legislation search; update Bills By The Numbers block to use filter by default

---

web/themes/custom/nysenate_theme/src/patterns/components/bill-item/bill-item.scss
web/themes/custom/nysenate_theme/src/patterns/components/featured-legislation/featured-legislation.twig
web/themes/custom/nysenate_theme/src/patterns/components/nysenate-social-buttons/nysenate-social-buttons.twig
web/themes/custom/nysenate_theme/src/patterns/global/colors/_colors.scss
web/themes/custom/nysenate_theme/src/patterns/global/global.scss
web/themes/custom/nysenate_theme/src/templates/paragraphs/paragraph--committee-featured-legislation.html.twig
web/themes/custom/nysenate_theme/src/templates/taxonomy-term/taxonomy-term--issues.html.twig

- Changes twitter label name on social shares
- Updates bird icon on issue pages and featured legislation block to X icon

X / Twitter updates

---

web/modules/custom/nys_bills/src/Form/BillForm.php

This commit was pushed using -n due to a number of pre-existing errors in code style.  Those issues will be resolved with a future commit.

Catch exception generated when senator has no associated user

---

web/themes/custom/nysenate_theme/nysenate_theme.libraries.yml
web/themes/custom/nysenate_theme/src/patterns/components/featured-story/featured-story.scss
web/themes/custom/nysenate_theme/src/patterns/global/base/_base.scss
web/themes/custom/nysenate_theme/src/patterns/global/utils/_classes.scss
web/themes/custom/nysenate_theme/src/templates/views/views-view-fields--home-majority-issue--home.html.twig

Forgot to reset these changes after fixing the theme weight issue

Fix max-width issue on dashboard, spacing on home budget block

---

composer.json
composer.lock
config/sync/core.extension.yml
config/sync/environment_indicator.settings.yml
web/sites/default/settings.php

update module, run updates, export config

Reinstall environment indicator module

---

config/sync/views.view.manage_student_submissions.yml

1. Move student name and teacher email into own columns
2. Add form type filter
3. Ensure export respects filters

NYS-316: Updates to manage student submissions view

---

composer.lock
config/sync/views.view.honoree_profiles.yml
web/modules/custom/nys_contrib_alters/nys_contrib_alters.module

**Core**
drupal/core (10.4.5 => 10.4.7)
**Contrib**
drupal/address (2.0.3 => 2.0.4)
drupal/charts (5.1.3 => 5.1.5)
drupal/colorbox (2.1.1 => 2.1.4): Security Update: https://www.drupal.org/sa-contrib-2025-041
drupal/inline_entity_form (3.0.0-rc20 => 3.0.0-rc21)
drupal/key (1.19.0 => 1.20.0):
drupal/node_export (1.3.0 => 1.4.0)
drupal/oembed_providers (2.2.1 => 2.2.2): Security update: https://www.drupal.org/sa-contrib-2025-048
drupal/search_api_solr (4.3.8 => 4.3.10): Security fix: https://www.drupal.org/project/search_api_solr/releases/4.3.10
drupal/stage_file_proxy (3.1.4 => 3.1.5): Security fix: https://www.drupal.org/sa-contrib-2025-035
drupal/upgrade_status (4.3.6 => 4.3.7):
drupal/views_autocomplete_filters (2.0.2 => 2.0.3)
drupal/views_list_sort (1.5.0 => 1.6.0) …

Core update 10.4.7

---

config/sync/field.field.paragraph.summer_reading.field_grade.yml
config/sync/field.storage.paragraph.field_grade.yml
config/sync/views.view.summer_reading_admin.yml
web/themes/custom/nysenate_theme/src/patterns/global/reading/reading.scss

Summer reading form date updates

---

.github/workflows/pantheon-deploy-dev-manual.yml
.github/workflows/pantheon-deploy-multidev.yml

Vendor folder included by updating script to bypass existing .gitignore file, which ignored vendor

Fix edge-case deploy issues by including vendor dir in build artifact
